# Generated by Django 5.0.4 on 2024-04-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=255)),
                ('car_version', models.CharField(max_length=255)),
                ('car_model', models.CharField(max_length=255)),
                ('car_price', models.IntegerField()),
            ],
        ),
    ]
